### ISSUE TITLE
Failure:      node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by NalinNair** [node-inspector/v8-debug#19]

**Comment by NalinNair** [comment]
1774 error Windows_NT 6.1.7601
1775 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nairns\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
1776 error node v5.1.1
1777 error npm  v3.5.1
1778 error code ELIFECYCLE
1779 error v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
1779 error Exit status 1
1780 error Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
1780 error Make sure you have the latest version of node.js and npm installed.
1780 error If you do, this is most likely a problem with the v8-debug package,
1780 error not with npm itself.
1780 error Tell the author that this fails on your system:
1780 error     node-pre-gyp install --fallback-to-build

**Comment by 3y3** [comment]
You try to instal outdated version on `v8-debug`. Please check version of dependencies in your package.
