### ISSUE TITLE
v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build` fails on node 8.2.1

### ISSUE THREAD

**Issue by mhornbacher** [node-inspector/v8-debug#43]
OS Platform: Node version 8.2.1 with npm 5.3.0 on Ubuntu 17.10

There seems to be an issue with Node 8 in this file: https://github.com/node-inspector/v8-debug/blob/master/src/debug.cc

Relating to a depreciated API call (new api source: https://github.com/v8/node/commit/293fc84613293b350d35a04a84801661b8c29bd9 )

**Comment by PCGeekBrain** [comment]
8.1.4 works fine.

**Comment by PCGeekBrain** [comment]
Attempted with v8-debug@1.0.1 and it still fails with the same error

**Comment by PCGeekBrain** [comment]
Seems like the issue is the reliance on this api call: https://github.com/v8/node/commit/293fc84613293b350d35a04a84801661b8c29bd9

**Comment by clintcambier** [comment]
If you look at the beginning of your errors, do you see anything related to Python? For me I had the wrong version installed. It needs to be v2.7. See: https://github.com/nodejs/node-gyp

**Comment by mhornbacher** [comment]
Sadly no, but on my system I have python 2.7 installed as `python` and python 3.6 under `python3`

**Comment by clintcambier** [comment]
Additionally, I downgraded my NodeJS from the latest (8.2.1 ) to the LTS 6.11.2. I think after this I was able to continue. Based on all my findings NodeJS 8.* won't work with this package.

**Comment by mhornbacher** [comment]
Same here except that I found version 1.0.1 does work with node 7.

I raised this issue because I think I found why it does not work in node 8. When my life returns to sanity I'll take a crack at making the change

**Comment by csilvers** [comment]
See also https://github.com/nodejs/node/issues/14411.  It sounds like not only does it not work now, things will only get worse with node 9.

**Comment by nodox** [comment]
I keep running into this issue and there seems to be no solution...

**Comment by greygatch** [comment]
My solution (was using grunt-node-inspector) was to completely remove this dependency. :(

If you're using v6.3 or greater, I'd suggest using the "built-in DevTools-based debugger which mostly deprecates Node Inspector" as an alternative.

**Comment by xflihaibo** [comment]
> v8-debug@1.0.1 install /Users/xxx/.nvm/versions/node/v10.15.3/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

**Comment by xflihaibo** [comment]
macos install error 
> v8-debug@1.0.1 install /Users/lihaibo/.nvm/versions/node/v10.15.3/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build
