### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by popomore** [node-inspector/v8-debug#6]
Can't get the tarball which is https://node-inspector.s3.amazonaws.com/debug/v0.3.1/node-v14-darwin-x64.tar.gz

```
> v8-debug@0.3.1 install /Users/popomore/nvm/v0.11.12/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/debug/v0.3.1/node-v14-darwin-x64.tar.gz
```

use curl to download the tarball

```
curl https://node-inspector.s3.amazonaws.com/debug/v0.3.1/node-v14-darwin-x64.tar.gz
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>debug/v0.3.1/node-v14-darwin-x64.tar.gz</Key><RequestId>13F97BBE9594E2F7</RequestId><HostId>iscPnFCCXR7obLuQydFeKfHPWw3zS71fJf9sr6fYO2leFWrmoqDFhPXbEnuahUur8Ta6UuuSnOs=</HostId></Error>%   
```

**Comment by AshCoolman** [comment]
binaries for `mac` would be useful

**Comment by 3y3** [comment]
I added some fixes to v8-profiler and v8-debug. Also I added prebuild binaries for Linux and OSX.
Please try to reinstall node-inspector now.

**Comment by popomore** [comment]
Is it not supported in 0.11.12?

**Comment by 3y3** [comment]
For unstable version I use 0.11.13 release (not 0.11.14, because there doesn't exist a correct Win x64 version).

Correct me, but it seems to me what 0.11.12 has corrupted binary packages system?
