### ISSUE TITLE
Installation failure under Python 2.6

### ISSUE THREAD

**Issue by mamacdon** [node-inspector/v8-debug#8]
This issue was originally reported against v8-profiler in [v8-profiler issue #48](https://github.com/node-inspector/v8-profiler/issues/48), but v8-debug has the same problem.

v8-debug 0.3.1, as published to npmjs.org [here](http://registry.npmjs.org/v8-debug/-/v8-debug-0.3.1.tgz), contains Windows line endings in its `binding.gyp` file:

```shell
$ wget http://registry.npmjs.org/v8-debug/-/v8-debug-0.3.1.tgz &> /dev/null
$ tar -xf v8-debug-0.3.1.tgz
$ grep -Pc "\x0D\x0A" package/binding.gyp 
12        # !!! Expected 0
```

This causes npm install to fail under Python 2.6:
```shell
$ python --version
Python 2.6.5
$ cd package && npm install --production .

> v8-debug@0.3.1 install /home/vcap/app/temp/v8-debug/package
> node-pre-gyp install --fallback-to-build

Traceback (most recent call last):
  File "/home/vcap/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/home/vcap/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "/home/vcap/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 527, in main
    return gyp_main(args)
  File "/home/vcap/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 503, in gyp_main
    options.circular_check)
  File "/home/vcap/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/home/vcap/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2692, in Load
    variables, includes, depth, check, True)
  File "/home/vcap/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 362, in LoadTargetBuildFile
    includes, True, check)
  File "/home/vcap/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 219, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/vcap/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:462:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
```

**Comment by 3y3** [comment]
I posted fixup today. Can you try to fork master HEAD and `npm install` it, to submit that fixup is correct (I don't have enviroment to test it by myself)

**Comment by 3y3** [comment]
I added some fixes to v8-profiler and v8-debug. Also I added prebuild binaries for Linux and OSX.
Please try to reinstall node-inspector now.

**Comment by mamacdon** [comment]
Using the prebuilt binaries, I can install node-inspector in my Ubuntu 10 environment. Thank you!

However, there remains a problem when `v8-debug` is built from source. Python 2.6 still chokes on `binding.gyp`, the same as before:

```shell
$ mkdir node_modules && npm install v8-debug@0.3.2
$ cd node_modules/v8-debug/
# Build from source, skipping prebuilt binary
$ node-pre-gyp install --build-from-source 
...
   File "binding.gyp", line 1                                                    
    {                                                                           
     ^                                                                          
SyntaxError: invalid syntax                                                     
gyp ERR! configure error                                                        
gyp ERR! stack Error: `gyp` failed with exit code: 1
```

I don't fully understand this, but there is some mismatch between the git repo, and what gets published to npmjs.org.
* If I clone the v8-debug repo, `binding.gyp` contains LF's. Build works OK.
* But in the published tarball, `binding.gyp` contains CRLF's. Build fails.

Is a Windows machine running the `npm publish` job? Maybe the repo needs to be re-cloned so that your earlier change to `.gitattributes` takes effect? I'm not sure...

**Comment by 3y3** [comment]
@mamacdon , thanks for feedback. I think after some rebases I missed the changes in binding.gyp line endings. Can you please confirm, that this problem was fully resolved for v8-profiler?

**Comment by mamacdon** [comment]
Verified that both `v8-debug@0.3.3` and `v8-profiler@5.2.2` build from source correctly.

Thanks again.
